apiVersion: v1
kind: ConfigMap
metadata:
  name: ms-consulta-documentos-segmento
  namespace: poc-nttdata
  labels:
    app: ms-consulta-documentos-segmento
data:
  errorCatalog.json: |
    {
      "errorDetails": [
        {
          "message": "Error comunicandose con servicio",
          "code": "MSOC_01",
          "httpCode": "500"
        }
      ]
    }