apiVersion: v1
kind: ConfigMap
metadata:
  name: ms-consulta-documentos-segmento-properties
  namespace: poc-nttdata
  labels:
    app: ms-consulta-documentos-segmento
data:
  PORT: "8080"
  JAVA_OPTS: "-Xmx512m -Xms100m"
  ERROR_CATALOG: "/opt/catalog/errorCatalog.json"